# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1adf44d34c789ce5f8d226c78968486367b7825972cabbb832a52cff870eed8699ca856f2ce341b6d3047bc848443e9057a7784bb83ff131e0d7204b5d618578

test:
  secret_key_base: 65c23b8f85adbe60c7f397e0f7324b49c6d514802227c94713b5ece18825bef5f41fc5078912135adebcc79e9f19146e5c5aaf7db3b591b31f76fd8b4c643b53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
